---
title: "Publications"
output: html_document
---

# Journal Articles

\

<div class="profile-details-wrapper">
<div data-badge-popover="left" data-badge-type="donut" data-doi="10.1177/1354066118791690" class="altmetric-embed"></div>
<div class="profile-details">
Kiran Phull, Gokhan Ciflikli, and Gustav Meibauer. __Gender and bias in the International Relations curriculum: Insights from reading lists.__ _European Journal of International Relations._ First Published August 20, 2018. https://doi.org/10.1177%2F1354066118791690
  </div>
</div>

\

# Works in Progress

Gokhan Ciflikli. __Unpacking the machine learning black box: Locally faithful explanations for classification algorithms.__

Machine learning approaches to conflict studies predominantly rely on predictive accuracy and variable importance to establish validity. However, directional effect---measured as coefficient values in traditional statistical approaches---are neither calculated nor reported. I address this shortcoming by implementing the open-source Local Interpretations of Model-agnostic Explanations (LIME) framework to a set of influential political science papers. In doing so, I demonstrate the value-added contribution of establishing the directionality of machine learning findings beyond that of variable importance.

Gokhan Ciflikli. __A unitary predictive model of conflict duration.__

This paper expands on the [Cunningham and Lemke (2013)](https://www.journals.cambridge.org/abstract_S0020818313000167) study on combining civil and interstate wars by including a large number of predictors taken from the rich civil war literature. The proposed framework unpacks the bargaining failure framework into three components governing power projection over distance, which I argue to be the main determinant of duration: material capability, politics, and geography. In doing so, I do not discriminate between the
‘types’ of war and provide a general theory of conflict duration. I employ predictive modelling techniques such as machine learning, deep learning, and ensemble methods to demonstrate that the majority of predictive covariates of war duration are indeed common to both civil and interstate wars. Further, in most cases, the direction of the effect holds across types, suggesting that the underlying mechanism operates in a similar fashion.

Gokhan Ciflikli and Nils Metternich. __Improving civil war duration prediction with ensemble learning.__

This paper introduces the first survival ensemble approach to improve predictive accuracy in conflict studies. We present a framework for making temporal forecasts of ethnic conflict build on actor and group configurations. Using EPR data to identify which ethnic groups are part of the government and rebel organizations, we build an ensemble tree model for ethnic conflict duration prediction. In comparison to mainstream statistical models, the random forest algorithm we employ reduces prediction error by at least 3\% and at most 26\% in existing influential studies on civil war duration.

Nils Metternich, Gokhan Ciflikli, Ali Altaf, and Tatjana Stankovic. __Predicting the severity of civil wars: An actor-centric approach.__

This paper introduces RebelTrack and RebelCast, which consist of a set of functions to measure rebel behaviour, characteristics, and configurations. Using mainly data from the UCDP GED dataset in combination with PRIO grid data, RebelTrack establishes an open-development platform to generate theory and data-driven information on rebel organizations. RebelTrack will be delivered as an R package with an open access Github platform for further development and improvement of existing indicators. The RebelTrack package with be updated yearly, with beta versions running on Github for users to access the latest indicators. RebelCast will also develop user-requested measures that will be included in the beta and annual releases. Data generation and data provision comply with the Data Access and Research Transparency (DA-RT) initiative, which enables researchers using RebelTrack to submit their work to the leading journals in political science and beyond. This includes the provision of a detailed codebook, download date and version number of original data, and the complete replication code.