---
title: "Gokhan Ciflikli, PhD | Cogentis Consulting"
output: html_document
---

👋 I'm Gökhan.

# Who I Am

A methodologist and a computational social scientist by training, I have 17 years of experience working in tech, open-source software development, and applied research.

In 2024, I founded **Cogentis Consulting** to work independently at growing startups and academic institutions. My expertise stems from doing a PhD from the London School of Economics (2017) and from the tech roles I held as Director of AI & ML at [Superside](https://www.superside.com/) (2023-2024), Head of Data & Analytics at [Attest](https://www.askattest.com/) (2019-2023), and Technical Lead at [Quanteda Initiative](https://quanteda.org/) (2017-2018).

I maintain an ongoing connection to cutting-edge academic research and community as a Senior Visiting Fellow at the [LSE Data Science Institute](https://www.lse.ac.uk/DSI) since 2023.

# What I Offer

Unlock the power of senior data leadership without the overhead of a full-time commitment. From **single-day workshops** and **one-off consulting** to all the way to **fractional data leadership**, I build bridges between academia and industry by combining the best of both worlds.

### From Academia to Industry

I build and enhance your Data, Analytics & AI functions. Whether you are looking to build your first Data function or looking to level up an existing organisation, I provide strategic leadership and execution across all stages of your data transformation journey.

**Scientific Rigour and Robust Methodology**

In the fast-paced world of business, it is extremely easy to fall into common pitfalls that undermine the validity and reliability of your findings. As an expert in statistical methodology, I help your business avoid the most prevalent mistakes that can skew results and drive poor decision-making.

**Applied Research for Business Impact**

Bridging the gap between academic research and real-world business applications is one of my core strengths. I specialise in translating state-of-the-art academic research into actionable insights that directly address the challenges and opportunities within your business domain.

------------------------------------------------------------------------

### From Industry to Academia

**Industry Outreach for Academic Research**

Drawing on my extensive network within data and tech leadership communities in the UK, I act as a liaison between your research team and the frontier companies in your domain of interest: accurate production data and realistic operational constraints contribute to increased validity of your experiments.

**Career Transition Coaching for PhDs and Postdocs**

Transitioning from academia to industry is a daunting process. I provide comprehensive career coaching, mentorship, and job placement support to help PhDs and postdocs pivot into high-impact roles in the business world.

> *It is the chief characteristic of the religion of science that it works. ---Asimov*
