---
title: "About"
output: html_document
---

Click [here](/img/Ciflikli_CV_260219.pdf) for my resume.

I'm a computational social scientist by training and a member of the [CSS London initiative](http://www.csslondoninitiative.co.uk/people/). I currently work as an analytic software developer for the [Quanteda Initiative](https://quanteda.org/people/) hosted at the [Methodology Department](http://www.lse.ac.uk/Methodology/People/Researchers/Gokhan-Ciflikli) of London School of Economics. My ongoing research primarily focuses on predictive modelling, political methodology relating to modelling binary-time-series-cross-sectional (BTSCS) data, out-of-sample cross-validation techniques, and making 'black box' machine learning findings more human-friendly.

More specifically, I am interested in exploring how inward looking (explanatory, in-sample) and outward looking (predictive, out-of-sample) social science research can be synthesized together with an emphasis on armed conflict onset and duration, which was the focus of my Ph.D dissertation. I am also a [research scientist](http://katalog.uu.se/profile/?id=N19-495) working on an automated newspaper reporting extraction project using natural language processing (NLP) at Uppsala University (Sweden), in conjunction 
with [Research Institutes of Sweden (RISE)](https://www.ri.se/en).

I take inspiration from physics, biology, and complex systems theory, which allow me to employ various [mainstream statistical](http://blogs.lse.ac.uk/impactofsocialsciences/2014/09/23/data-science-statistics-communication/) and [machine learning](https://xkcd.com/1838/) tools to solve various social science problems at hand. Most of my work is on [GitHub](https://github.com/ciflikli). I happily contribute my posts to [R-Bloggers](https://www.r-bloggers.com/), a hub for all things R that I have learned a lot from, and [RWeekly](https://rweekly.org/). Check out [R-Users](https://www.r-users.com/) as well, a job posting platform for R enthusiasts.

Other than all the serious-sounding stuff above, I also enjoy dabbling in NBA analytics (Let's Go #LakeShow!), writing dystopian sci-fi, and graphic design.